### PR TITLE
fix: handle resource names with hyphens

### LINKED ISSUE #2436: [Container] Some function names being generated with hyphens
This is a new codegen regression. The function `GoogleApis.Container.V1.Api.Projects.container_projects_locations_clusters_well-known_get_openid-configuration` is getting generated with a name that includes hyphens, which of course fails to compile. The hyphens need to be replaced with underscores.

### PR DESCRIPTION
**Pull request by dazuma**
Fixes #2436 

Some resource names have hyphens, which is currently messing with codegen since an Elixir function name cannot (easily) include hyphens. This currently affects the GKE API.

This PR replaces hyphens with underscores when generating function names.

### CODE REVIEW

File: lib/google_apis/generator/elixir_generator/endpoint.ex [hunk 1]
```diff
@@ -257,7 +257,7 @@ defmodule GoogleApis.Generator.ElixirGenerator.Endpoint do
 
   defp method_name_to_endpoint_name(method_name) do
     method_name
-    |> String.replace(".", "_")
+    |> String.replace(~r{[\.-]}, "_")
```
Comment (chingor13) [inline lib/google_apis/generator/elixir_generator/endpoint.ex]: does the `-` not need an escape character?

Comment (dazuma) [reply lib/google_apis/generator/elixir_generator/endpoint.ex]: No it doesn't.
